services:
  app:
    build:
      context: docker/app
    command: /bin/sh -c "rm -f tmp/pids/server.pid && ./bin/dev"
    volumes:
      - ./:/app
      - bundle-volume:/usr/local/bundle
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - redis
  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
volumes:
  bundle-volume:
    driver: local
  redis-data:
    driver: local
